[package]
name = "marmot_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.11.0"
assert_approx_eq = "1.1.0"
mockall = "0.10.2"

